src/TaskBundle/Entity/Task.php
<?php
namespace TaskBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use TaskBundle\Entity\Traits\BlameableTrait;
use TaskBundle\Entity\Traits\TimestampableTrait;
use Symfony\Component\Validator\Constraints as Assert;
use Hateoas\Configuration\Annotation as Hateoas;

/**
 * @Hateoas\Relation(
 *      "self",
 *      href = @Hateoas\Route(
 *          "task_show",
 *          parameters = { "task" = "expr(object.getId())" }
 *      )
 * )
 *
 * @ORM\Entity(repositoryClass="TaskBundle\Repository\TaskRepository")
 * @ORM\Table(name="task")
 */
class Task
{
    const STATUS_OCZEKUJACY = 10;
    const STATUS_WYKONANY = 20;
    const STATUS_ODRZUCONY = 30;

    const STATUSES_TRANS = [
        self::STATUS_OCZEKUJACY => "app.task.status.oczekujacy",
        self::STATUS_WYKONANY => "app.task.status.wykonany",
        self::STATUS_ODRZUCONY => "app.task.status.odrzucony"
    ];

    use TimestampableTrait;
    use BlameableTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deadline;

    /**
     * @ORM\OneToMany(targetEntity="TaskBundle\Entity\Task", mappedBy="parentTask")
     */
    private $childTasks;


    /**
     * @ORM\ManyToOne(targetEntity="TaskBundle\Entity\Task", inversedBy="childTasks")
     * @ORM\JoinColumn(nullable=true)
     */
    private $parentTask;

    /**
     * @ORM\ManyToOne(targetEntity="TaskBundle\Entity\User", inversedBy="task")
     * @ORM\JoinColumn(nullable=true)
     */
    private $assignedTo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status = self::STATUS_OCZEKUJACY;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return mixed
     */
    public function getDeadline()
    {
        return $this->deadline;
    }

    /**
     * @param mixed $deadline
     */
    public function setDeadline($deadline)
    {
        $this->deadline = $deadline;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->childTasks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add childTask.
     *
     * @param \TaskBundle\Entity\Task $childTask
     *
     * @return Task
     */
    public function addChildTask(\TaskBundle\Entity\Task $childTask)
    {
        $childTask->setParentTask($this);
        $this->childTasks[] = $childTask;

        return $this;
    }

    /**
     * Remove childTask.
     *
     * @param \TaskBundle\Entity\Task $childTask
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeChildTask(\TaskBundle\Entity\Task $childTask)
    {
        $childTask->setParentTask(null);
        return $this->childTasks->removeElement($childTask);
    }

    /**
     * Get childTasks.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getChildTasks()
    {
        return $this->childTasks;
    }

    /**
     * Set parentTask.
     *
     * @param \TaskBundle\Entity\Task|null $parentTask
     *
     * @return Task
     */
    public function setParentTask(\TaskBundle\Entity\Task $parentTask = null)
    {
        $this->parentTask = $parentTask;

        return $this;
    }

    /**
     * Get parentTask.
     *
     * @return \TaskBundle\Entity\Task|null
     */
    public function getParentTask()
    {
        return $this->parentTask;
    }

    /**
     * Set assignedTo.
     *
     * @param \TaskBundle\Entity\User|null $assignedTo
     *
     * @return Task
     */
    public function setAssignedTo(\TaskBundle\Entity\User $assignedTo = null)
    {
        $this->assignedTo = $assignedTo;

        return $this;
    }

    /**
     * Get assignedTo.
     *
     * @return \TaskBundle\Entity\User|null
     */
    public function getAssignedTo()
    {
        return $this->assignedTo;
    }

    /**
     * @return mixed|string
     * @author Karol Włodek
     */
    public function getStatusText(){
        if(isset(self::STATUSES_TRANS[$this->getStatus()]))
        {
            return self::STATUSES_TRANS[$this->getStatus()];
        }
        else
        {
            return 'app.task.status.undefined';
        }
    }
}

src/TaskBundle/Form/TaskType.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 1/28/18
 * Time: 12:31 AM
 */

namespace TaskBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use TaskBundle\Entity\Task;

class TaskType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @author Karol Włodek
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, ["label" => "app.task.field.title"])
            ->add('description', null, ["label" => "app.task.field.description"])
            ->add('assignedTo', null, ["label" => "app.task.field.assignedTo"])
            ->add('deadline', DateTimeType::class,
                ["required" => false, "date_widget" => "single_text", "label" => "app.task.field.deadline"])
            ->add('submit', SubmitType::class, ["attr" => ["class" => "btn-primary"], "label" => "app.submit"]);
    }

    /**
     * @param OptionsResolver $resolver
     * @author Karol Włodek
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            "data_class" => Task::class
        ]);
    }
}

src/TaskBundle/Controller/TaskController.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 1/26/18
 * Time: 1:12 AM
 */

namespace TaskBundle\Controller;


use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\View\View;
use Nelmio\ApiDocBundle\Annotation\Model;
use Swagger\Annotations as SWG;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use TaskBundle\Entity\LogEntry;
use TaskBundle\Entity\Task;
use TaskBundle\Form\TaskType;

/**
 * @Route("/api")
 * Class TaskController
 * @package TaskBundle\Controller
 */
class TaskController extends FOSRestController
{
    /**
     * @Route("/task/{task}/delete", name="task_delete")
     * @param Task $task
     * @return Response
     * @author Karol Włodek
     */
    public function deleteAction(Task $task)
    {
        $em = $this->getDoctrine()->getManager();
        $tr = $this->get("translator");
        try {
            $em->remove($task);
            $em->flush();
            $this->addFlash("error", $tr->trans("app.task.delete_success"));

            $this->get('app.log.action')->addLog(Task::class, $task->getId(), LogEntry::LOG_TASK_REMOVE);
        } catch (\Exception $e) {
            $this->addFlash("danger", $tr->trans("app.task.delete_fail"));
        }

        return $this->redirectToRoute("task_list");
    }

    /**
     * @Route("/task/{task}/change_status", name="task_change_status")
     * @author Karol Włodek
     * @param Request $request
     * @param Task $task
     * @return Response
     */
    public function taskChangeStatusAction(Request $request, Task $task)
    {
        $em = $this->getDoctrine()->getManager();
        $status = $request->get("status");

        $statuses = [Task::STATUS_OCZEKUJACY, Task::STATUS_WYKONANY, Task::STATUS_ODRZUCONY];
        if (in_array($status, $statuses)) {
            $task->setStatus($status);

            $em->persist($task);
            $em->flush();

            return new Response("", Response::HTTP_OK);
        }

        return new Response("", Response::HTTP_BAD_REQUEST);
    }

    /**
     * @SWG\Response(
     *   response = 200,
     *     description="Returned when successful."
     * )
     *
     * @Rest\Get("/tasks", name="task_list")
     * @Rest\Get("/")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function getTasksAction()
    {
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository(Task::class);

        $view = $this->view($repo->findAll())->setTemplate("TaskBundle:Task:list.html.twig")->setTemplateVar('tasks');

        return $this->handleView($view);
    }

    /**
     * @SWG\Response(
     *   response = 200,
     *     description="Returned when successful."
     * )
     *
     * @Rest\Get("/tasks_assigned", name="task_list_assigned")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function getMyListAction()
    {
        $user = $this->getUser();

        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository(Task::class);

        $tasks = $repo->findByUser($user);

        $view = $this->view($tasks)->setTemplate("TaskBundle:Task:my_list.html.twig")->setTemplateVar('tasks');

        return $this->handleView($view);
    }

    /**
     *
     * @SWG\Response(
     *   response = 201,
     *     description="Created"
     * )
     *
     * @Rest\Post("/tasks", name="task_new_post")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $task->setStatus(Task::STATUS_OCZEKUJACY);
            $em->persist($task);
            $em->flush();

            $this->addFlash("success", $this->get('translator')->trans("app.task.created"));

            return $this->redirectToRoute("task_edit", ["task" => $task->getId()]);
        } else {
            $errors = $form->getErrors();
            foreach ($errors as $error) {
                $this->addFlash("error", $error->getMessage());
            }
        }

        $view = $this->view($form->createView())->setTemplate('TaskBundle:Task:new.html.twig')->setTemplateVar("form");
        return $this->handleView($view);
    }

    /**
     *
     * @SWG\Response(
     *   response = 200,
     *     description="Success"
     * )
     *
     * @Rest\Get("/task/new", requirements={"_format" = "html"}, name="task_new")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function newFormAction(Request $request)
    {
        $form = $this->createForm(TaskType::class);
        $view = $this->view($form->createView())->setTemplate('TaskBundle:Task:new.html.twig')->setTemplateVar("form");

        return $this->handleView($view);
    }

    /**
     * Get a specific post.
     *
     * @SWG\Response(
     *   response="200",
     *   description="Success",
     *   @Model(type=Task::class)
     * )
     *
     * @Rest\Get("/tasks/{task}", name="task_show", requirements={"id" = "\d+"})
     *
     * @return View
     */
    public function showAction(Task $task)
    {
        $view = $this->view($task)->setTemplate('TaskBundle:Task:show.html.twig')->setTemplateVar("task");
        return $this->handleView($view);
    }

    /**
     *
     * @SWG\Response(
     *   response = 200,
     *     description="Success"
     * )
     *
     * @Rest\Get("/tasks/{task}/edit", requirements={"_format" = "html"}, name="task_edit")
     *
     * @param Request $request
     * @param Task $task
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editFormAction(Task $task)
    {
        $form = $this->createForm(TaskType::class, $task);
        $view = $this->view($form->createView())->setTemplate('TaskBundle:Task:edit.html.twig')->setTemplateVar("form");

        return $this->handleView($view);
    }

    /**
     * @SWG\Response(
     *   response = 201,
     *     description="Created"
     * )
     *
     * @Rest\Post("/tasks/{task}", name="task_edit_post")
     *
     * @param Request $request
     * @param Task $task
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, Task $task)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($task);
            $em->flush();

            $this->addFlash("success", $this->get('translator')->trans("app.task.modified"));

            return $this->redirectToRoute("task_show", ["task" => $task->getId()]);
        } else {
            $errors = $form->getErrors();
            foreach ($errors as $error) {
                $this->addFlash("error", $error->getMessage());
            }
        }

        $view = $this->view($form)->setTemplate('TaskBundle:Task:edit.html.twig')->setTemplateVar("form");
        return $this->handleView($view);
    }
}

src/TaskBundle/Resources/views/Task/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% form_theme form 'bootstrap_3_layout.html.twig'  %}
    {{ form(form, {"action": path("task_edit_post", {task: form.vars.data.id})}) }}
    <a href="{{ path("task_list") }}" class="btn btn-default" title="{{ "app.task.list"|trans }}">{{ "app.task.list"|trans }}</a>
    <a href="{{ path("task_new") }}" class="btn btn-default" title="{{ "app.task.new"|trans }}">{{ "app.task.new"|trans }}</a>
{% endblock %}

{% block title %}
    {{ "app.task.new"|trans }}
{% endblock %}

src/TaskBundle/Resources/views/Task/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "app.task.list"|trans }}{% endblock %}
{% block body %}

    <div class="row">
        <div class="col-xs-12">
            <h4>{{ "app.task.list"|trans }}</h4>
        </div>
        <div class="col-xs-12">
            <a class="btn btn-primary" href="{{ path("task_new") }}"
               title="{{ "app.task.new"|trans }}">{{ "app.task.new"|trans }}</a>
        </div>
        <div class="col-xs-12">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>{{ "app.task.field.title"|trans }}</th>
                    <th>{{ "app.task.field.description"|trans }}</th>
                    <th>{{ "app.task.field.assignedTo"|trans }}</th>
                    <th>{{ "app.task.field.deadline"|trans }}</th>
                    <th>{{ "app.task.field.status"|trans }}</th>
                    <th>{{ "app.actions"|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for task in tasks %}
                    <tr>
                        <td><a href="{{ path("task_show", {task: task.id}) }}"
                               title="{{ "app.task.show"|trans }}">{{ task.id }}</a></td>
                        <td>{{ task.title }}</td>
                        <td>{{ task.description|slice(0, 255) }}</td>
                        <td>{% if task.assignedTo is not null %}{{ task.assignedTo.username }}{% else %}---{% endif %}</td>
                        <td>{% if task.deadline is not null %}{{ task.deadline|date('Y-m-d') }}{% else %}---{% endif %}</td>
                        <td>{{ task.statusText|trans }}</td>
                        <td>
                            <a href="{{ path("task_edit", {task: task.id}) }}"
                               title="{{ "app.task.edit"|trans }}" class="btn btn-info"><span class="fa fa-edit"></span></a>
                            <a href="{{ path("task_delete", {task: task.id}) }}"
                               title="{{ "app.task.edit"|trans }}" class="btn btn-danger"><span class="fa fa-remove"></span></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

src/TaskBundle/Resources/views/Task/my_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ "app.task.my_list"|trans }}
{% endblock %}

{% block body %}
    {% import _self as self %}
    <h4>{{ "app.task.my_list"|trans }}</h4>
    <div class="row">
        <div class="col-xs-4">
            {{ "app.task.todo_list"|trans }}
            <ul id="sortable_todo" class="connectedSortable"
                data-status="{{ constant("TaskBundle\\Entity\\Task::STATUS_OCZEKUJACY") }}">
                {% for task in tasks if task.status == constant("STATUS_OCZEKUJACY", task) %}
                    {{ self.sortableItem(task) }}
                {% endfor %}
            </ul>
        </div>
        <div class="col-xs-4">
            {{ "app.task.do_list"|trans }}
            <ul id="sortable_do" class="connectedSortable"
                data-status="{{ constant("TaskBundle\\Entity\\Task::STATUS_WYKONANY") }}">
                {% for task in tasks if task.status == constant("STATUS_WYKONANY", task) %}
                    {{ self.sortableItem(task) }}
                {% endfor %}
            </ul>
        </div>
        <div class="col-xs-4">
            {{ "app.task.done_list"|trans }}
            <ul id="sortable_done" class="connectedSortable"
                data-status="{{ constant("TaskBundle\\Entity\\Task::STATUS_ODRZUCONY") }}">
                {% for task in tasks if task.status == constant("STATUS_ODRZUCONY", task) %}
                    {{ self.sortableItem(task) }}
                {% endfor %}
            </ul>
        </div>

        <div class="col-xs-12">
            <div id="panel-task">

            </div>
        </div>
    </div>
{% endblock %}


{% macro sortableItem(task) %}
    <li class="ui-state-default" data-item="{{ task.id }}">
        <p>{{ task.title }}</p>
        <small>{{ task.description|slice(0,50) }}</small>
    </li>
{% endmacro %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <style>
        .connectedSortable {
            width: 100%;
            border: 1px solid #eee;
            min-height: 120px;
            list-style-type: none;
            margin: 0;
            padding: 5px 0 0 0;
            margin-right: 10px;
        }

        .connectedSortable li {
            margin: 0 5px 5px 5px;
            padding: 5px;
            font-size: 1.2em;
            width: 120px;
        }
    </style>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".connectedSortable").sortable({
                connectWith: ".connectedSortable",
                receive: function (event, ui) {
                    var $item = ui.item;

                    changeStatus($item.attr("data-item"), $(this).attr("data-status"));
                }
            }).disableSelection();

            /**
             * Triggers change status request
             * @param id
             */
            function changeStatus(id, status) {
                var url = Utils.getUrl("task_change_status", [id]);

                $.ajax({
                    url: url,
                    method: "POST",
                    data: {
                        status: status
                    }
                });
            }

            function showPanel(id)
            {
                var url = Utils.getUrl("task_show_panel", [id]);
                $.ajax({
                    url: url,
                    method: "GET",
                    data: {
                        status: status
                    }
                });
            }
        });
    </script>
{% endblock %}

src/TaskBundle/Resources/views/Task/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% form_theme form 'bootstrap_3_layout.html.twig'  %}
    {{ form(form, {"action": path("task_new_post")}) }}
    <a href="{{ path("task_list") }}" class="btn btn-default" title="{{ "app.task.list"|trans }}">{{ "app.task.list"|trans }}</a>
{% endblock %}

{% block title %}
    {{ "app.task.new"|trans }}
{% endblock %}

src/TaskBundle/Resources/views/Task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ "app.task.show"|trans }}
{% endblock %}

{% block body %}
    <h4>{{ "app.task.details"|trans({"%name%": task.title}) }}</h4>

    <table class="table">
        <thead>
        <tr>
            <th>{{ 'app.task.show_params'|trans }}</th>
            <th>{{ 'app.task.show_value'|trans }}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ "app.task.field.title"|trans }}</td>
            <td>{{ task.title }}</td>
        </tr>
        <tr>
            <td>{{ "app.task.field.description"|trans }}</td>
            <td>{{ task.description }}</td>
        </tr>
        {% if task.assignedTo is not null %}
            <tr>
                <td>{{ "app.task.field.assignedTo"|trans }}</td>
                <td>{{ task.assignedTo.username }}</td>
            </tr>
        {% endif %}
        {% if task.description is not null %}
            <tr>
                <td>{{ "app.task.field.deadline"|trans }}</td>
                <td>{{ task.deadline|date("Y-m-d") }}</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{{ path("task_edit", {task: task.id}) }}" class="btn btn-primary"
       title="{{ "app.task.edit"|trans }}">{{ "app.task.edit"|trans }}</a>
    <a href="{{ path("task_list") }}" class="btn btn-default"
       title="{{ "app.task.list"|trans }}">{{ "app.task.list"|trans }}</a>
{% endblock %}